### PR TITLE
get it compiling again

### PR DESCRIPTION
**Pull request by gregwebs**
not sure if the stuff that I commented out was useful for something

[Review on Reviewable](https://reviewable.io/reviews/haskell-distributed/azure-service-api/1)

### CODE REVIEW

**Comment by hyperthunk** [comment]
Hi Greg. I have to admit, I'm not greatly enthused by this pull request. Removing the upper bounds on the library dependencies is a controversial decision, and whilst personally I'm not in love with upper bounds (since they can be a real pain) I'm not sure that just removing them is the right thing to do either. You've not explained why you've done this for some but not all the dependencies, leaving me no clue about your intention or the reason behind the change.

You've commented out the binary instance for AzureSetup - how do you expect to serialize it without one?

You've introduced `withSocketsDo` and changed the way the HTTP response body is handled, without offering any explanation why this is better (or more correct) than what was there in the first place?

Even though this _compiles_, there's no way I can merge it as it stands. If you can offer some rationale behind the changes then we can discuss them and resolve any issues that are preventing you from working with HEAD.

**Comment by gregwebs** [comment]
This pull request is meant to be a starting point on a discussion to get this library working again. I hope we can have a friendly and collaborative discourse and avoid confrontational tones when they aren't necessary.

The main issue with HEAD right now is that it does not install (I tried with cabal-dev on Linux). I think this shows that the current strict bounds did not work well, but definitely the bounds in this pull request can be improved.

The response body is being handled the same, but the http-conduit API has changed in recent versions. The http-conduit documentation recommends using withSocketsDo.

Where are you using the binary instance for AzureSetup?

**Comment by hyperthunk** [comment]
Greg, I apologize if my tone sounded aggressive. It wasn't my intention to get into a bun-fight about this and I'm totally amenable to making improvements.

> The main issue with HEAD right now is that it does not install (I tried with cabal-dev on Linux). I think this shows that the current strict bounds did not work well, but definitely the bounds in this pull request can be improved.

I don't mind loosening them if it makes sense to do so, but I'd prefer to raise the upper bounds rather than remove them.

> The http-conduit documentation recommends using withSocketsDo.

That's an initialization function that only needs to be called once when the executable is starting. My inclination is to let the application deal with initialising the network layer, rather than putting that call into every execution, not least because it's confusing to read.

In the context of Cloud Haskell, a network-transport (or CH topology management backend like simplelocalnet) would typically be responsible for doing that. Other applications might do things differently.

On non-windows platforms, that call with of course do nothing. On windows however, it breaks out to a system call which might be harmless (in terms of effects) but will trigger a context switch which will likely hurt the performance of unbound (i.e., `forkIO`) threads. So putting it in `azureExecute` is a no-no.

> Where are you using the binary instance for AzureSetup?

The distributed-process-azure Cloud Haskell backend has to pass various bits of information around (using TCP/IP rather than HTTP) during deployment, and the `AzureSetup` is one of them. Also in general, any type that needs to be transmittable in Cloud Haskell has to implement `Serializable`, which requires an instance of `Typeable` _and_ `Binary` to be present.

**Comment by gregwebs** [comment]
Thanks for the good code review. At this point I am not sure if it makes sense for me to use this library for what I need. I will let you know.

**Comment by hyperthunk** [comment]
> Thanks for the good code review. At this point I am not sure if it makes sense for me to use this library for what I need. I will let you know.

OK that's fair enough. If you feel that the library could do a better job of offering a more general-purpose API, feel free to make recommendations. We could work around the need for `binary` in this library by putting a proxy type into distributed-process-azure and serializing that instead, if that would make this library more usable for applications that don't need Cloud Haskell. If you feel that's important - i.e., if it is the `binary` dependency that is putting you off using this library - then let me know and I'll file a bug to look into doing that on https://cloud-haskell.atlassian.net.

**Comment by gregwebs** [comment]
I am ok with binary, but the API of things being serialized changed in newer versions of the libraries so it was no longer working for me. I am more concerned about the hxt dependency which is not in my stack and takes a long time to compile.

BTW, if you are trying to reduce the overhead of azureExecute then you would not want to be calling withManager inside it but rather have an existing manager available so that connections can be re-used.

**Comment by hyperthunk** [comment]
@gregwebs - good point about re-using `withManager`, we will look into that.

**Pull request closed without merging**
